Update init script

diff --git a/etc/init.d/git-deploy b/etc/init.d/git-deploy
--- a/etc/init.d/git-deploy
+++ b/etc/init.d/git-deploy
@@ -14,57 +14,72 @@
 # description: git-deploy daemon
 # processname: git-deploy
 
+. /lib/lsb/init-functions
+
 DAEMON_PATH="/usr/bin/"
 
 DAEMON="git-deploy server"
 
 NAME=git-deploy
 DESC="Git deployement tool"
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
+PIDFILE=/var/run/$DAEMON.pid
+SCRIPTNAME=/etc/init.d/$DAEMON
 
 case "$1" in
 start)
-	printf "%-50s" "Starting $NAME..."
-	cd $DAEMON_PATH
-	PID=`$DAEMON > /dev/null 2>&1 & echo $!`
-	#echo "Saving PID" $PID " to " $PIDFILE
-        if [ -z $PID ]; then
-            printf "%s\n" "Fail"
-        else
-            echo $PID > $PIDFILE
-            printf "%s\n" "Ok"
-        fi
-;;
-status)
-        printf "%-50s" "Checking $NAME..."
         if [ -f $PIDFILE ]; then
             PID=`cat $PIDFILE`
             if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
-                printf "%s\n" "Process dead but pidfile exists"
+                log_action_msg "$PIDFILE exists..."
             else
-                echo "Running"
+                log_action_msg "$NAME is running"
+                exit 0
+            fi
+        fi
+        log_daemon_msg "Starting $NAME" "$DAEMON"
+
+        cd $DAEMON_PATH
+        $DAEMON > /dev/null 2>&1 &
+        PID=$!
+        if [ -z $PID ]; then
+            log_end_msg 1
+        else
+            echo $PID > $PIDFILE
+            log_end_msg 0
+        fi
+;;
+status)
+        log_action_msg "Checking $NAME..."
+        if [ -f $PIDFILE ]; then
+            PID=`cat $PIDFILE`
+            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
+                log_action_msg "Process dead but pidfile exists"
+                exit 3
+            else
+                log_action_msg "$NAME is running"
             fi
         else
-            printf "%s\n" "Service not running"
+            log_action_msg "$NAME is not running"
+            exit 3
         fi
 ;;
 stop)
-        printf "%-50s" "Stopping $NAME"
-            PID=`cat $PIDFILE`
-            cd $DAEMON_PATH
+        log_daemon_msg "Stopping $NAME"
+        cd $DAEMON_PATH
         if [ -f $PIDFILE ]; then
+            PID=`cat $PIDFILE`
             kill -HUP $PID
-            printf "%s\n" "Ok"
+            log_end_msg 0
             rm -f $PIDFILE
         else
-            printf "%s\n" "pidfile not found"
+            log_action_msg "pidfile not found, maybe $NAME is not running ? check it by pgrep to be sure"
+            log_end_msg 0
         fi
 ;;
 
 restart)
-  	$0 stop
-  	$0 start
+        $0 stop
+        $0 start
 ;;
 
 *)
